### ISSUE TITLE
How to generate novel ligand use user defined protein pocket

### ISSUE THREAD

**Issue by Kartinaa** [bytedance/DecompOpt#2]
Dear author,

Thank you for sharing the code for your wonderful work—it’s really intriguing! I have a question about sampling molecules for my protein. Should I place the PDB file of the pocket in the `./data` directory and simply run the `sample_compose.sh` script? Or do I need to modify the script to sample from a customized protein?

I’d really appreciate any hints you could provide on this. Many thanks for your time!

**Comment by laviaf** [comment]
Thank you for your question! The current sampling script is only for target proteins in the Crossdoecked2020 test set. In order to sample for a customized protein, the prior information of arms and scaffold should be provided. We will upload a sampling script for customized proteins very soon.

**Comment by Kartinaa** [comment]
Thanks for your reply! Looking forward to see your script!
